### ISSUE TITLE
能否增加对macos的客户端的支持

### ISSUE THREAD

**Issue by cmodog** [emptysuns/Hi_Hysteria#36]
RT

**Comment by emptysuns** [comment]
我没mac,不过hy项目给了编译好的darwin[可执行文件](https://github.com/HyNetwork/hysteria/releases/download/v1.0.3/hysteria-tun-darwin-10.12-arm64),你照着改改输出的`config.json`,直接run就行了。

欢迎提交pr完善这部分

**Comment by Chasing66** [comment]
@cmodog docker, docker-compose 会用的话，那这个改一改
```
version: '3.9'
services:
  hysteria:
    image: tobyxdd/hysteria
    container_name: hysteria
    restart: always
    ports:
      - "5678:5678"
      - "5679:5679"
    volumes:
      - /root/hysteria:/root
    command: ["--config", "/root/hysteria.json"]
    logging: 
      driver: "local"
      options:
        max-size: "1m"
```
