### ISSUE TITLE
stash客户端连不上

### ISSUE THREAD

**Issue by BrightVan** [emptysuns/Hi_Hysteria#47]
vps网络安全组打开了udp的对应端口（不知是不是这里错了），可确实应该是udp协议啊，
安装时选择的协议类型是：1、udp(QUIC)。
默认的就是IPV4优先，不知为何lsof 显示的TYPE是IPV6
stash 配置如下(auth就是自己的设置的口令字符型吧，Stash官方示例的注释没看明白)：
```yaml
- name: "VPS.XX"
  type: hysteria
  server: xxx.mydomain.com
  port: myport
  up-speed: 100 # 上传带宽（单位：Mbps）
  down-speed: 312 # 下载带宽（单位：Mbps）
  auth: xxxxxxxxxxxx # bytes encoded in base64
  alpn:
    - h3
```
